name: debt_tracker
description: A visual debt/paydown tracking app

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  stacked: ^1.5.7
  stacked_services: ^0.3.2+1
  get_it: ^4.0.2
  get: ^2.10.1
  injectable: ^0.4.0+1
  auto_route: ^0.5.0
  json_annotation: ^3.0.0

  # Logging
  catcher: ^0.3.6
  sentry: '>=3.0.0 <4.0.0'

  # Firebase
  firebase_remote_config: ^0.3.1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6

  # Syncfusion
  syncfusion_flutter_core: ^18.1.54
  syncfusion_flutter_charts: ^18.1.54
  syncfusion_flutter_gauges: ^18.1.54

  flutter_form_builder: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  auto_route_generator: ^0.5.0
  injectable_generator: ^0.4.1
  json_serializable: ^3.2.0

flutter:
  uses-material-design: true
